### ISSUE TITLE
add a new feature

### ISSUE THREAD

**Issue by limatiga** [dllz/EnforcerLua#1]
I think enforcer need a new feature like add link to admin in /adminlist and add a /msglink command.

**Comment by limatiga** [comment]
And i think i was wrong submitted a new feature in issues tab.

**Comment by dllz** [comment]
@limatiga No that is fine.

**Comment by dllz** [comment]
@limatiga Can u explain further what u mean by this?

**Comment by limatiga** [comment]
@dllz a feature to get link from chat with /msglink command.
so when we reply to the message with /msglink command, the bot will answer the link of that chat. ex : https://telegram.me/WerewolfAlliance/328078

**Comment by dllz** [comment]
@limatiga This already exists. Get your admin to set the link with /link <link>. Then when you send /link it replies with the link

**Comment by Olgabrezel** [comment]
I am pretty sure, that that is not what @limatiga wanted. I don't really know if this exists in groups, but in channels, every sent message has its own link, and when you klick it, you are directly sent to the message. If such links do exist in groups, her issue was to create a /msglink command which works by reply and the enforcer returns to you the link to the message which the /msglink command was replying to. I hope, you understand me!
