### ISSUE TITLE
Feature Suggestion: Automatic Tempban

### ISSUE THREAD

**Issue by Olgabrezel** [dllz/EnforcerLua#13]
Is there a reason why @werewolfbutlerbot cannot tempban automatically (eg in the spam settings or when reached the maximum number of warns)? I'd really like do set the settings like "If someone received 3 warns, tempban him for a week". So is there a reason why it is not possible? If there is not, I'd really like this feature to be added!

**Comment by matteoxin** [comment]
@Olgabrezel I really support this, I think it should be added because it's a cool feature to have. But tempbans should be improved, for example when doing /status.
