### ISSUE TITLE
Link to group in reports

### ISSUE THREAD

**Issue by michelleized** [dllz/EnforcerLua#14]
Is it possible to have the link to group with every report? Admins can manually /setlink and it appears in evert unsolved and solved report.

**Comment by TheZeus121** [comment]
@michelleized Link to group or link to message? 
Link to group is possible, but link to message only in public groups.

**Comment by michelleized** [comment]
@TheZeus121 Link to group please, at least for private groups. I already know that link to message is not possible in private groups...

**Comment by dllz** [comment]
Will be implemented in E5
