### ISSUE TITLE
Admin not receiving reports from enforcer but can still PM them

### ISSUE THREAD

**Issue by BlaQPhoeniX** [dllz/EnforcerLua#17]
enforcer won't send reports to waffles (from any of the groups waffles is admin in), but will send them to other admins, and will respond to waffles both in pm and on the group, and solved still works. stopped working sept 1st

171857657
Waffles
@wafflesbetabot

**Comment by dllz** [comment]
@BlaQPhoeniX Thanks for reminding me

**Comment by dllz** [comment]
Any username that ends in bot wont get reports from the bot as the bot will assume it is a bot.
