### ISSUE TITLE
Final round bug

### ISSUE THREAD

**Issue by FernandoTBarros** [dllz/EnforcerLua#2]
We were playing a normal game with 8 players.
In the second night, the wolf ate the drunk. And then left two players, the wolf and the cursed.
The game goes on, passes the voting, and just finished after the next action of the wolf, who was eat the cursed.
We thought that is a bug, the game was not to end after the wolf eat the drunk?

**Comment by michelleized** [comment]
@FernandoTBarros Hi! Thanks for reporting, however this is where you report issues for Enforcer (Butler bot).
You can report issues any of the game bots (WW Moderator 1, 2 and Beta bot) here: https://github.com/parabola949/Werewolf/issues

**Comment by FernandoTBarros** [comment]
Yes, sorry! I've read the channel today and didn't read right! hehe
I've already post it on the right place!
Thanks!

**Comment by michelleized** [comment]
@FernandoTBarros Yup, saw it! Thank you! :)
