### ISSUE TITLE
Unable to ban by ID

### ISSUE THREAD

**Issue by michelleized** [dllz/EnforcerLua#3]
Admins are not able to ban using ID. When **/ban idnumber** is used, we get the message **Reply to someone**. Already checked if user has joined the group, it still does not work.

**Comment by michelleized** [comment]
/banid works but displays error message that enforcer "has never seen this user before"

**Comment by TheZeus121** [comment]
Yes, I know, will look into it asap (that's not very soon tho.)

**Comment by dllz** [comment]
Minor bugs remains

**Comment by michelleized** [comment]
Minor bug report (not priority) this is the message that comes out when /banid and /kickid are used:
"I've never seen this user before.
If you want to teach me who they are, forward me a message from them"
Tho the command works fine and it doesn't say "this is a bug blah blah report using ! command" anymore.
