### ISSUE TITLE
Solved reports remain unsolved in PM

### ISSUE THREAD

**Issue by jeffffc** [dllz/EnforcerLua#5]
Reports were made, then solved in group, but some of the admins got solved report in PM but some didnt.

Group ID: -1001090943575
Affected Admin: @Vincthe 241885056

PM showed as solved:
![image](https://cloud.githubusercontent.com/assets/15724935/19412263/cc3fec24-9344-11e6-98a2-7bd29dc55236.jpeg)
but not in here:
![image](https://cloud.githubusercontent.com/assets/15724935/19412264/cc9c6850-9344-11e6-85de-c0aaa5602896.jpeg)

**Comment by dllz** [comment]
Telegram is sending null for the message id in the private chat with the user. Sadly the issue can not be resolved on our side. The only chance enforcer is not editing it would from the user name including the word bot in it
