### ISSUE TITLE
/adminlist update

### ISSUE THREAD

**Issue by CloneMMDDCVII** [dllz/EnforcerLua#7]
Add admins usernames in /adminlist so we can contact them more efficiently.

**Comment by dllz** [comment]
They were removed because it tags all the admins when ever someone sends /adminlist

**Comment by CloneMMDDCVII** [comment]
@dllz Maybe add a pm option then ?

**Comment by dllz** [comment]
Already exists, if the group admins set it to pm it to the user. Only problem is people dont start the bot so no one uses it.
