### ISSUE TITLE
About the Global Banlist

### ISSUE THREAD

**Issue by MidnightLycanroc** [dllz/EnforcerLua#8]
Is it possible to implement a function to ignore the global banlist under config?

I have a small private group that's open for certain people sharing the same interest and a couple of them were in the global banlist, but aren't really flouting any rules inside that chat (yet).

The Enforcer is a better alternative as you could report simply using @admin instead of requiring them to tag an admin (which may or may not be present).

Also, is it possible to implement a "cooldown" to warns issued to the **same** person? It happened before that several admins are online at a time and got someone banned when we admins issued multiple warnings at the same time... x_x 

(Plus we don't know how to unban him, poor guy.)

**Comment by dllz** [comment]
@MidnightLycanroc you can unban him by going /unban @user the rest we will consider

**Comment by MidnightLycanroc** [comment]
Ah yes Ukko told me about /unban, although I'm not sure if it's intended but using /user on someone it would present you with a choice "?? Ban" which I have no idea what it does (unless it just bans a person).

**Comment by matteoxin** [comment]
@MidnightLycanroc It was an emoji turned into the "??", I don't actually know why, not that of an issue tbh

**Comment by MidnightLycanroc** [comment]
Ah okay, thanks. I'll just wait for for the response for the suggestion then~.

**Comment by dllz** [comment]
@MatteoIlGrande probably the way telegram handles emojis now, it can be fixed though. /unban has that intented use though and allows you to just use the username which can be useful. In the meantime use that, also what is your particular interest that people who have been globally banned fit in?

**Comment by dllz** [comment]
@MidnightLycanroc yes /unban has that intented use though and allows you to just use the username which can be useful. In the meantime use that, also what is your particular interest that people who have been globally banned fit in?

**Comment by MidnightLycanroc** [comment]
Well he's doing pretty okay in the group that I'm monitoring.

Because I'm a pretty neutral person, I don't wish to have people just banned because they got banned by a global admin. 

But however if they still commit the same thing in the groups that I'm monitoring, I will not hesitate to just ban them as well.

**Comment by dllz** [comment]
@MidnightLycanroc interesting can you please send me your group id and the ids of the people in question?

**Comment by MidnightLycanroc** [comment]
I will apologise first to be holding you back at the moment, I need to discuss this with the other admins as well about providing you the IDs of the group and people. 

It's quite late here right now so I might either have someone to discuss this with you afterwards or we would converse again in about 17 hours' time.
