### ISSUE TITLE
Suggestion: improve /status

### ISSUE THREAD

**Issue by matteoxin** [dllz/EnforcerLua#9]
Improve the command /status 
Instead of only showing
"Test (@username) is banned from the group"
It should display which admin banned and the reason 
For example: Ponyta (@MatteoIlGrande) banned the user for ads

**Comment by dllz** [comment]
[https://github.com/dllz/Enforcer2/commit/7d245cd8714e25bdd32e4c214d9fd25da8ac0c28](Solved) Solved
