### ISSUE TITLE
Suggestion: Show TelegramId in all kick/ban/warn messages

### ISSUE THREAD

**Issue by Dabadooba** [dllz/EnforcerLua#9]
Telegram Id should be shown in all messages from the bot, (warns, flood kicks/bans, arabic language bans....). This would make looking up users who were banned then changed their username much easier.

**Comment by dllz** [comment]
This is a lot more work than it should be

**Comment by dllz** [comment]
Coming in the next update

**Comment by CloneMMDDCVII** [comment]
@dllz ❤️
